version: '2'

services:
    app:
      build: .
      volumes:
        - .:/usr/src
      volumes_from:
        - redis
      command: bash -c 'python setup.py develop && exec sleep infinity'

    redis:
      image: redis:3
      user: root
      volumes:
        - /var/run/redis
        - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      command: bash -c 'redis-server /usr/local/etc/redis/redis.conf'

    rabbitmq:
      image: rabbitmq:3
      volumes:
        - rabbitmq:/var/lib/rabbitmq
      environment:
        - "RABBITMQ_DEFAULT_VHOST=example-vhost"

volumes:
  rabbitmq: {}

